add jokes skeletons
diwash007/Joker.py pull request #7
Opened 2022-10-04 16:37 UTC by rizkyian78

2022-10-04 16:42 UTC, diwash007 requested changes
One joke for 1 Pull Request is a very bad idea, my friend. Please add at least 20 valid non-duplicate jokes/puns.

2022-10-04 17:03 UTC, rizkyian78 commented
okay will do man

2022-10-05 01:38 UTC, rizkyian78 commented
alreay done man

2022-10-05 12:46 UTC, diwash007 approved these changes
LGTM

2022-10-05 12:46 UTC, merged